### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by jayvdb** [suurjaak/SQLitely#1]
```py
Traceback (most recent call last):
  File "setup.py", line 23, in <module>
    from sqlitely import conf
  File "/tmp/metaextract_jy52cx5a/SQLitely-1.2/sqlitely/__init__.py", line 1, in <module>
    from . import conf
  File "/tmp/metaextract_jy52cx5a/SQLitely-1.2/sqlitely/conf.py", line 16, in <module>
    from ConfigParser import RawConfigParser
ModuleNotFoundError: No module named 'ConfigParser'
```

**Comment by suurjaak** [comment]
Python 3 is yet unsupported.

**Comment by suurjaak** [comment]
Python 3 support now available.
